services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@55w0rd
      POSTGRES_DB: CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always
    
